- name: Ec2 get facts
  ec2_instance_info:
    region: "us-east-1"
    filters:
      instance-state-name: [ "running","instance_id" ]
  register: ec2
-      
  debug:
      var: ec2.instance_id
           
