-
      name: Terminate instances that were previously launched
      ec2:
        region: 'us-east-1'
        state: 'absent'
        instance_ids: '{{ item }}'
      with_items: "{{ instance_id }}"
