-
      name: Terminate instances that were previously launched
      ec2:
        region: 'us-east-1'
       # state: 'absent'
        instance_ids: '{{ ec2.instance_id }}'
      register: abc
-      
      debug:
            var: abc
           
